services:
  db:
    image: postgres:15
    container_name: students-postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
